export const EmployeeData = [
  {
    employee_id: 101,
    first_name: "Alice",
    last_name: "Johnson",
    email: "alice.johnson@example.com",
    position: "Software Engineer",
    department: "Engineering",
    salary: 80000,
  },
  {
    employee_id: 102,
    first_name: "Bob",
    last_name: "Smith",
    email: "bob.smith@example.com",
    position: "Product Manager",
    department: "Product",
    salary: 90000,
  },
  {
    employee_id: 103,
    first_name: "Carol",
    last_name: "Williams",
    email: "carol.williams@example.com",
    position: "Data Analyst",
    department: "Data Science",
    salary: 70000,
  },
  {
    employee_id: 104,
    first_name: "David",
    last_name: "Brown",
    email: "david.brown@example.com",
    position: "HR Manager",
    department: "Human Resources",
    salary: 75000,
  },
  {
    employee_id: 105,
    first_name: "Eve",
    last_name: "Martinez",
    email: "eve.martinez@example.com",
    position: "UX Designer",
    department: "Design",
    salary: 85000,
  },
  {
    employee_id: 106,
    first_name: "Frank",
    last_name: "Garcia",
    email: "frank.garcia@example.com",
    position: "Marketing Specialist",
    department: "Marketing",
    salary: 65000,
  },
  {
    employee_id: 107,
    first_name: "Grace",
    last_name: "Miller",
    email: "grace.miller@example.com",
    position: "Sales Representative",
    department: "Sales",
    salary: 60000,
  },
  {
    employee_id: 108,
    first_name: "Hank",
    last_name: "Davis",
    email: "hank.davis@example.com",
    position: "DevOps Engineer",
    department: "Engineering",
    salary: 95000,
  },
  {
    employee_id: 109,
    first_name: "Ivy",
    last_name: "Lopez",
    email: "ivy.lopez@example.com",
    position: "Customer Support",
    department: "Support",
    salary: 55000,
  },
  {
    employee_id: 110,
    first_name: "Jack",
    last_name: "Gonzalez",
    email: "jack.gonzalez@example.com",
    position: "Finance Manager",
    department: "Finance",
    salary: 90000,
  },
];
