export const BookList = [
  {
    title: "To Kill a Mockingbird",
    author: "Harper",
    yearPublished: 1960,
    genres: ["Fiction", "Classics"],
    availableCopies: 3,
    ratings: { reviewer: "Yvonne", rating: 4.4 },
  },
  {
    title: "1984",
    author: "Goerge",
    yearPublished: 1949,
    genres: ["Dystopian", "Science Fiction"],
    availableCopies: 5,
    ratings: { reviewer: "Yvonne", rating: 4.2 },
  },
  {
    title: "The Great Gatsby",
    author: "Scott",
    yearPublished: 1925,
    genres: ["Fiction", "Classics"],
    availableCopies: 2,
    ratings: { reviewer: "Yvonne", rating: 3.4 },
  },
  {
    title: "Moby Dick",
    author: "Herman",
    yearPublished: 1851,
    genres: ["Adventure", "Classics"],
    availableCopies: 1,
    ratings: { reviewer: "Yvonne", rating: 5 },
  },
  {
    title: "Pride and Prejudice",
    author: "Jane",
    yearPublished: 1813,
    genres: ["Romance", "Classics"],
    availableCopies: 4,
    ratings: { reviewer: "Yvonne", rating: 4.9 },
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D",
    yearPublished: 1951,
    genres: ["Fiction", "Classics"],
    availableCopies: 2,
    ratings: { reviewer: "Yvonne", rating: 3.0 },
  },
  {
    title: "The Hobbit",
    author: "J.R.R",
    yearPublished: 1937,
    genres: ["Fantasy", "Adventure"],
    availableCopies: 5,
    ratings: { reviewer: "Yvonne", rating: 4.2 },
  },
  {
    title: "War and Peace",
    author: "Leo",
    yearPublished: 1869,
    genres: ["Historical", "Classics"],
    availableCopies: 3,
    ratings: { reviewer: "Yvonne", rating: 4.8 },
  },
  {
    title: "The Odyssey",
    author: "Homer",
    yearPublished: -800,
    genres: ["Epic", "Classics"],
    availableCopies: 4,
    ratings: { reviewer: "Yvonne", rating: 3.4 },
  },
  {
    title: "Crime and Punishment",
    author: "Fyodor",
    yearPublished: 1866,
    genres: ["Philosophical", "Classics"],
    availableCopies: 3,
    ratings: { reviewer: "Yvonne", rating: 2.5 },
  },
];
